### ISSUE TITLE
Parse data error

### ISSUE THREAD

**Issue by ghost** [wintercoder/datamaker#1]
![image](https://user-images.githubusercontent.com/13285922/38462129-c8fb72c2-3b13-11e8-8d91-d4dd8a4e7168.png)

![image](https://user-images.githubusercontent.com/13285922/38462132-d35d5ba4-3b13-11e8-9ab7-e9f680a190cb.png)

![image](https://user-images.githubusercontent.com/13285922/38462134-d86ba362-3b13-11e8-8c6d-88781340fea2.png)

**Comment by ghost** [comment]
拿到首尾括号内的内容属于所有字段，然后基于`,`判断每一个字段，进而分析字段的类型等。

**Comment by wintercoder** [comment]
已修
