### ISSUE TITLE
您好大佬，您的这个工具非常好用，我想向您请教一个问题

### ISSUE THREAD

**Issue by 2540461056** [wintercoder/datamaker#10]
您的功能中有一个“常量列表(组模式)”，也即是可以自己划定几个值，然后在这个划定范围内随机挑选值注入；请问在sql中有这个函数吗？或者在sql中如何实现这个功能？请您方便时回复我一下，谢谢！！

**Comment by wintercoder** [comment]
select  ELT( 
	FLOOR(1 + (RAND() * 6))
	,'a','b','c','d','e','f'); 

只适合工具场景下使用，不建议在业务逻辑里使用哈

**Comment by 2540461056** [comment]
好的！！！！我知道了，谢谢您，好人一生平安！！！
