### ISSUE TITLE
请问最多500行一组么

### ISSUE THREAD

**Issue by youngsailor** [wintercoder/datamaker#11]
请问最多500行一组么？

**Comment by wintercoder** [comment]
> 请问最多500行一组么？

因为代码是直接部署在我的小服务器上的，怕有人恶意搞事设置999999之类的，烧我宽带，加了限制500，正常使用的话500也基本能满足诉求了，如果你想要很大批量的数据，建议在本地搭建，相关限制：
 https://github.com/wintercoder/datamaker/blob/master/index.php 第402行
