### ISSUE TITLE
会把create代码里的index误认为是字段

### ISSUE THREAD

**Issue by peter17ji** [wintercoder/datamaker#8]
CREATE TABLE `cust_graph` (
	`id` VARCHAR(32) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`cust_id` VARCHAR(32) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`merchant_id` VARCHAR(32) NULL DEFAULT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`graph_outer_id` VARCHAR(32) NOT NULL COLLATE 'utf8mb4_0900_ai_ci',
	`create_time` DATETIME NULL DEFAULT NULL,
	`reset_time` DATETIME NULL DEFAULT NULL,
	PRIMARY KEY (`id`) USING BTREE,
	INDEX `merchant_id` (`merchant_id`) USING BTREE,
	INDEX `cust_id` (`cust_id`) USING BTREE,
	INDEX `graph_outer_id` (`graph_outer_id`) USING BTREE,
	INDEX `cust_id_merchant_id` (`cust_id`, `merchant_id`) USING BTREE
)
COLLATE='utf8mb4_0900_ai_ci'
ENGINE=InnoDB
;
后面四个index会被误认为是字段

**Comment by wintercoder** [comment]
我周末有时间就修一下~我记得以前处理过，可能后来修BUG的时候修坏了
